on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Latest Release

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Create Release
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        # List of GOOS and GOARCH pairs from `go tool dist list`
        goosarch:
          - 'windows/amd64'
          - 'windows/arm64'
          - 'linux/amd64'
          - 'linux/arm64'
          - 'darwin/amd64'
          - 'darwin/arm64'
          # etc
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '1.23.1'
      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o "nomi-whatsapp-linux-amd64" -v
          GOOS=linux GOARCH=arm64 go build -o "nomi-whatsapp-linux-arm64" -v
          GOOS=windows GOARCH=amd64 go build -o "nomi-whatsapp-windows.exe" -v

      - name: Upload windows binary
        uses: actions/upload-artifact@v4
        with:
          name: 'nomi-whatsapp-windows.exe'
          path: 'dist/nomi-whatsapp-windows.exe'

      - name: Upload linux-amd64 binary
        uses: actions/upload-artifact@v4
        with:
          name: 'nomi-whatsapp-linux-amd64'
          path: 'dist/nomi-whatsapp-linux-amd64'

      - name: Upload linux-arm64 binary
        uses: actions/upload-artifact@v4
        with:
          name: 'nomi-whatsapp-linux-arm64'
          path: 'dist/nomi-whatsapp-linux-arm64'

      - name: Release Notes
        run:
          git log $(git describe HEAD~ --tags --abbrev=0)..HEAD --pretty='format:* %h %s%n  * %an <%ae>' --no-merges >> ".github/RELEASE-TEMPLATE.md"
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          body_path: ".github/RELEASE-TEMPLATE.md"
          draft: true
          files: |
            dist/nomi-whatsapp-windows.exe
            dist/nomi-whatsapp-linux-amd64
            dist/nomi-whatsapp-linux-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}